from docx import Document
from docx.shared import Pt
from docx.oxml.ns import qn
from io import BytesIO
from datetime import datetime

def generate_word_report(df):
    doc = Document()
    doc.add_heading("Malaria Investigation Summary", 0)

    for col in df.columns:
        para = doc.add_paragraph()
        para.add_run(col + ": ").bold = True
        para.add_run(str(df[col][0]))

    doc.add_paragraph("\nGenerated by: Dr. Mohammedelnagi Mohammed", style="Intense Quote")

    # Watermark-style footer
    section = doc.sections[-1]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = "All rights reserved © Dr. Mohammedelnagi Mohammed"
    footer_para.style.font.size = Pt(8)

    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
